In [1]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_table("regress.txt", header=None, sep=" ")

In [6]:
data.columns = ("Observation", "Wage", "log(Wage)", "Education", "Education^2", "Education*log(Wage)")

In [7]:
data

Observation   Wage  log(Wage)  Education  Education^2  Education*log(Wage)
0             1  37.93       3.64         18          324                65.44
1             2  40.87       3.71         18          324                66.79
2             3  14.18       2.65         13          169                34.48
3             4  16.83       2.82         16          256                45.17
4             5  33.17       3.50         16          256                56.03
5             6  29.81       3.39         18          324                61.11
6             7  54.62       4.00         16          256                64.00
7             8  43.08       3.76         18          324                67.73
8             9  14.42       2.67         12          144                32.03
9            10  14.90       2.70         16          256                43.23
10           11  21.63       3.07         18          324                55.44
11           12  11.09       2.41         16          256                38.50
12           13  10.00       2.30         13          169                29.93
13           14  31.73       3.46         14          196                48.40
14           15  11.06       2.40         12          144                28.84
15           16  18.75       2.93         16          256                46.90
16           17  27.35       3.31         14          196                46.32
17           18  24.04       3.18         16          256                50.76
18           19  36.06       3.59         18          324                64.53
19           20  23.08       3.14         16          256                50.22

In [10]:
Y = np.array(data["log(Wage)"])

In [11]:
Y

array([3.64, 3.71, 2.65, 2.82, 3.5 , 3.39, 4.  , 3.76, 2.67, 2.7 , 3.07,
       2.41, 2.3 , 3.46, 2.4 , 2.93, 3.31, 3.18, 3.59, 3.14])

In [13]:
a = np.ones(20)

In [21]:
Y.shape

(20,)

In [22]:
X = np.array([data.Education, a])

TypeError: 'tuple' object is not callable

In [17]:
X

array([[18., 18., 13., 16., 16., 18., 16., 18., 12., 16., 18., 16., 13.,
        14., 12., 16., 14., 16., 18., 16.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [18]:
X.shape

(2, 20)

In [19]:
X = X.transpose

In [20]:
X = np.array

<function ndarray.transpose>

In [23]:
X

<function ndarray.transpose>

In [36]:
data["Ones"] = np.ones(20)

In [37]:
data.head()

Observation   Wage  log(Wage)  Education  Education^2  Education*log(Wage)  \
0            1  37.93       3.64         18          324                65.44   
1            2  40.87       3.71         18          324                66.79   
2            3  14.18       2.65         13          169                34.48   
3            4  16.83       2.82         16          256                45.17   
4            5  33.17       3.50         16          256                56.03   

   Ones  
0   1.0  
1   1.0  
2   1.0  
3   1.0  
4   1.0

In [49]:
X = np.array([data.Education, data.Ones]).reshape((20,2))

In [53]:
X1 = np.array(data.Education)

In [54]:
X1.shape

(20,)

In [55]:
X2 = np.array(data.Ones)

In [56]:
X2.shape

(20,)

In [57]:
numpy?

Object `numpy` not found.


In [67]:
X = np.array([data.Education, data.Ones])

In [69]:
X = X.T

In [70]:
X

array([[18.,  1.],
       [18.,  1.],
       [13.,  1.],
       [16.,  1.],
       [16.,  1.],
       [18.,  1.],
       [16.,  1.],
       [18.,  1.],
       [12.,  1.],
       [16.,  1.],
       [18.,  1.],
       [16.,  1.],
       [13.,  1.],
       [14.,  1.],
       [12.,  1.],
       [16.,  1.],
       [14.,  1.],
       [16.,  1.],
       [18.,  1.],
       [16.,  1.]])

In [74]:
(np.linalg.inv(X.T*X))*((X.T)*Y)

ValueError: operands could not be broadcast together with shapes (2,20) (20,2) 

In [78]:
Y.shape

(20,)

In [80]:
np.dot(X.T, Y)

array([995.73,  62.63])

In [82]:
Beta = np.dot(np.linalg.inv(np.dot(X.T, X)), np.dot(X.T, Y))

In [83]:
Beta

array([0.15509975, 0.69643392])